steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - attributes
  - --region=europe-west1
  - --trigger-topic=facebook_data
  - --memory=1024MB
  - --timeout=540s
  - --runtime=python311
  - --allow-unauthenticated
  - --min-instances=0
  - --max-instances=1
  - --source=.